spring:
  bot:
    plugin-list: # 配置插件列表（有序），如果插件返回0，继续执行剩余插件，如果插件返回1，终止剩余插件执行
      - moe.iacg.miraiboot.plugin.LogPlugin # 日志插件
      - moe.iacg.miraiboot.plugin.DemoPlugin # 测试插件
      - moe.iacg.miraiboot.plugin.HelloPlugin # 测试插件


server:
  port: 8081

nacos:
  config:
    bootstrap:
      enable: true
    server-addr: localhost:8848
    data-id: mirai-boot-client
    auto-refresh: true
    type: properties

